### ISSUE TITLE
Safari pinned tab

### ISSUE THREAD

**Issue by san650** [san650/ember-web-app#15]
Add option for Safari pinned tab

`<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#b91d47">`

**Comment by jrjohnson** [comment]
@san650 I'm going to take a shot at adding this. Would you prefer this be added as a `target` in an icon with a new property for the `color`? Or as a `pinnedTabs` key under the `apple` specific configuration?

**Comment by san650** [comment]
I think adding it as a target is a good idea, with the new `color` prop. What do you think?

**Comment by jrjohnson** [comment]
Makes complete sense to me. I will give it a try and report back if it gets weird.
