### ISSUE TITLE
Support fingerprinting and prefixing of manifest.json file with broccoli-asset-rev

### ISSUE THREAD

**Issue by san650** [san650/ember-web-app#22]
* Generate fingerprinting for `manifest.json` file
* Use broccoli-asset-rev's `prepend` option
* Add the correct file name to the meta tag `<meta name="manifest"...`
* Allow to turn off the fingerprinting of `manifest.json` file (or at least document how to do it with `broccoli-asset-rev`).

**Comment by sivakumar-kailasam** [comment]
I tried taking a stab at this but the node tests seem flaky that they timed out without processing anything. Is that a known issue? (Hadn't looked into tests deep enough to uncover what the cause might be)

**Comment by san650** [comment]
No, they never timed out on my machine or the CI.

I'm using [ember-cli-addon-tests](https://github.com/tomdale/ember-cli-addon-tests) for the add-on's acceptance tests. These tests take a lot of time to run, there's a `timeout` configuration in the tests. Try with a higher timeout to see if they fail. See https://github.com/san650/ember-web-app/blob/b040482dd717be9ea8c6aa6cdd8be0e6fbf62376/node-tests/acceptance/manifest-test.js#L7
