### ISSUE TITLE
Allow prefix url as an option

### ISSUE THREAD

**Issue by sivakumar-kailasam** [san650/ember-web-app#37]
Having a prefix option for the manifest file would bring it to parity with how other assets are defined on the index.html page. Because assets are defined as `{{rootURL}}assets` they usually resolve to `/assets`. In addition when users define a prefix value it becomes `https://foo.cdn.io/assets`.  

So in our case the rootURL is `/` but we have a different `routerURL` and we load this app in a sub-path of our main app via proxy, there `/manifest.json` is undesirable. Having prefix there would've been useful.

**Comment by san650** [comment]
@sivakumar-kailasam thanks for reporting the issue! This is definitely something we have to support.

**Comment by san650** [comment]
@sivakumar-kailasam I'm looking into this issue but I need more information about it.

Right now, the add-on respects `rootURL` configuration, so if you change `rootURL` to be `/foo/bar/`, then the generated link tag would be:

```html
<link rel="manifest" href="/foo/bar/manifest.json">
```

__This is working fine as far I can tell__.

Can you explain a bit more what's the issue you're facing? Having an example or the configurations you're using would be super useful!

At the moment we don't process the `manifest.json` file with `broccoli-asset-rev` so adding fingerprinting or prefixing with asset-rev's `prepend` option won't work. There's a feature request for adding support for it #22.

**Comment by sivakumar-kailasam** [comment]
You seem to collect the fingerprint config from the consuming app, but seem to be missing out on the prepend value from [broccoli-asset-rev](https://github.com/rickharrison/broccoli-asset-rev/blob/master/README.md). If this value used along with rootURL, then it will be on par with other static assets of an app.

**Comment by san650** [comment]
Thanks for your promptly reply :bowtie:. I now see what's the issue.

Right now we're not processing the URL of `manifest.json` with `broccoli-asset-rev` so the manifest is not being fingerprinted nor prefixed. Issue #22 intends to tackle that.

I'll close this issue in favor of #22. I'll also update the description of that issue so it's more clear.

Please, feel free to continue the discussion on #22.
