### ISSUE TITLE
Blueprints assume jshint is being used

### ISSUE THREAD

**Issue by hidnasio** [san650/ember-web-app#45]
Since ember-cli 2.12.0 the default linter is eslint. This addon always generates manifest.json with a jshint configuration. It would be nice if the addon could detect which linter is being used.

Current configuration `/*jshint node:true*/`
Expected for projects using eslint `/* eslint-env node */`

**Comment by san650** [comment]
I'll change the blueprints to generate the `eslint` version. It doesn't make sense to keep having jshint.
