### ISSUE TITLE
Resources on `icons` best practices?

### ISSUE THREAD

**Issue by samselikoff** [san650/ember-web-app#60]
Thanks for this awesome addon!

Do you have any links to resources on what we should put in the `icons` array? It might be nice to link to some best practices or good defaults.

**Comment by YoranBrondsema** [comment]
I've found this website to be very useful in understanding the requirements of all the different platforms: https://realfavicongenerator.net/faq. They also have a checker tool: https://realfavicongenerator.net/favicon_checker.

**Comment by san650** [comment]
@samselikoff I use the same service @YoranBrondsema mentioned https://realfavicongenerator.net/faq which has really good info.

Is this enough?

Feel free to reopen the issue if you need more info.
