### ISSUE TITLE
Add og:site_name?

### ISSUE THREAD

**Issue by samselikoff** [san650/ember-web-app#61]
Should we add an `og:site_name` tag and derive its value from `name` or `short_name`?

I had to add

```
<meta property="og:site_name" content="EmberMap">
```

manually to my site's index.html to get this title to show up in Slack's unfurling.

**Comment by san650** [comment]
I'm not sure if this addon should handle open graph metadata, it seems more appropriate for a specific addon like [ember-meta-meta](https://emberobserver.com/addons/ember-meta-meta).

My concern is that `og:site_name` is more related to a _share_ functionality than a progressive web application and I don't want to extend the scope of the project beyond that (like adding support for random metadata).

Feel free to make a case for it and reopen the issue 😃 .
