### ISSUE TITLE
Issue with Apple Status Bar, Theme and Background settings

### ISSUE THREAD

**Issue by ChristopherJohnson25** [san650/ember-web-app#89]
Is anyone having issues with these settings? I'm not able to update anything in these settings, it's defaulting to white every time. What am I doing wrong? manifest.js below...

```
/* eslint-env node */
'use strict';

module.exports = function(/* environment, appConfig */) {
  // See https://github.com/san650/ember-web-app#documentation for a list of
  // supported properties

  return {
    name: "Viti",
    short_name: "Viti",
    description: "An app for finding the closest vineyards to you.",
    start_url: "/",
    display: "standalone",
    background_color: "#202020",
    theme_color: "#202020",
    icons: [
    ],
    apple: {
      statusBarStyle: 'black-translucent'
    },
    ms: {
      tileColor: '#202020'
    }
  };
}
```

**Comment by san650** [comment]
@ChristopherJohnson25 I think that in iOS for the status-bar color it will take the background color of `<body>` element or the background color of the `<html>`. Can you try changing these and see what happens?

**Comment by ChristopherJohnson25** [comment]
@san650 I'll try that and let you know. Thanks!

**Comment by san650** [comment]
@ChristopherJohnson25 any news about this?

I'll close the issue in the meantime, feel free to reopen it if my previous suggestion doesn't fix the issue.
