### ISSUE TITLE
Looking for maintainer

### ISSUE THREAD

**Issue by san650** [san650/ember-web-app#91]
I haven't been able to keep up with all the work that is needed to have the addon updated to the latest version of ember and adding all the requested features.

I would love to transfer the repo to someone that wants to continue the development of the addon.

**Comment by bobisjan** [comment]
Hi @san650 👋,

I'm open to maintain your add-on.

I was also thinking about moving your repository under some PWA related (and also non-user specific) organization, eq. @ember-pwa, but this org already exists, and the purpose is currently hidden to me. 

So, I'm not sure what is the good path forward for now 🙈.

Regardless, thank you for your work on this add-on 👏.

**Comment by san650** [comment]
> I'm open to maintain your add-on.

👏 awesome @bobisjan !

> I was also thinking about moving your repository under some PWA related (and also non-user specific) organization, eq. @ember-pwa, but this org already exists, and the purpose is currently hidden to me.
> So, I'm not sure what is the good path forward for now 🙈.

What I would suggest is:

* Fork the repo in your user
* I can update the description of this repo and the README to point to your fork as the new official one
* Create a new release using your fork, update all the references in the README and package.json to the new repo
* I'll give you ownership of the package in npm

What do you think about this plan? Github allows to transfer issues between repos now, so we can transfer the issues that make sense to your fork.

**Comment by bobisjan** [comment]
@san650, sounds good 👍.

> Fork the repo in your user

I already have a personal fork of your repository, but I would prefer to go under [zonkyio/ember-web-app](https://github.com/zonkyio/ember-web-app), so others from @zonkyio/ember can participate, if you are OK with that?

> Create a new release using your fork, update all the references in the README and package.json to the new repo

Does this (reference changes) need major version bump?

Thanks

**Comment by bobisjan** [comment]
@san650, the repository is forked under https://github.com/zonkyio/ember-web-app, so we can advance in following steps.

**Comment by san650** [comment]
@bobisjan I've updated the README and repo description to point to your fork. Could you send me your npm username?. You can send me that info in an email and we can continue there. (san650 at gmail).
